schema_version = "1.0.0"

id = "brv_blender_render_view"    
name = "[BRV] Blender Render View"
version = "0.1.0"
maintainer = "Eisteed <hello@eisteed.com>"
tagline  = "External render view working as a classic IPR"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

wheels = [
    "./wheels/PySide6-6.6.1-cp38-abi3-win_amd64.whl",
    "./wheels/shiboken6-6.6.1-cp38-abi3-win_amd64.whl",
    "./wheels/pywin32-306-cp311-cp311-win_amd64.whl",
    "./wheels/pillow-11.1.0-cp311-cp311-win_amd64.whl",
    "./wheels/pygetwindow-0.0.9-py3-none-any.whl",
    "./wheels/pymsgbox-1.0.9-py3-none-any",
    "./wheels/pyrect-0.2.0-py2.py3-none-any.whl",
    "./wheels/pyscreeze-0.1.30-py3-none-any.whl",
]
