schema_version = "1.0.0"

id = "brv_blender_render_view"    
name = "[BRV] Blender Render View"
version = "0.3.0"
maintainer = "Eisteed <hello@eisteed.com>"
website = "https://github.com/Eisteed/blender-render-view"
tagline  = "External render view working as a classic IPR"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64"]

wheels = [
    "./wheels/PySide6-6.6.0-cp38-abi3-win_amd64.whl",
    "./wheels/PySide6_Essentials-6.6.0-cp38-abi3-win_amd64.whl",
    "./wheels/PySide6_Addons-6.6.0-cp38-abi3-win_amd64.whl",
    "./wheels/shiboken6-6.6.0-cp38-abi3-win_amd64.whl",
    "./wheels/pywin32-310-cp311-cp311-win_amd64.whl",
    "./wheels/PyGetWindow-0.0.9-py3-none-any.whl",
    "./wheels/PyRect-0.2.0-py2.py3-none-any.whl"
]

[permissions]
files = "Export PNG to disk"
